export const mockAuthor = [
  {
    name: '李白',
    avatar: 'https://ziyuan.guwendao.net/authorImg300/libai.jpg',
    dynasty: '唐代',
    desc: '李白（701年－762年） ，字太白，号青莲居士，又号“谪仙人”，祖籍陇西成纪（今甘肃省秦安县），出生于蜀郡绵州昌隆县（一说出生于西域碎叶）。唐代伟大的浪漫主义诗人，被后人誉为“诗仙”，与杜甫并称为“李杜”，为了与另两位诗人李商隐与杜牧即“小李杜”区别，杜甫与李白又合称“大李杜”。据《新唐书》记载，李白为兴圣皇帝（凉武昭王李暠）九世孙，与李唐诸王同宗。其人爽朗大方，爱饮酒作诗，喜交友。李白深受黄老列庄思想影响，有《李太白集》传世，诗作中多为醉时写就，代表作有《望庐山瀑布》《行路难》《蜀道难》《将进酒》《早发白帝城》等。',
    proseNum: 1129,
    famousSentenceNum: 5980,
  },
  {
    name: '苏轼',
    avatar: 'https://ziyuan.guwendao.net/authorImg300/sushi.jpg',
    dynasty: '宋代',
    desc: '苏轼，（1037年1月8日-1101年8月24日）字子瞻、和仲，号铁冠道人、东坡居士，世称苏东坡、苏仙，汉族，眉州眉山（四川省眉山市）人，祖籍河北栾城，北宋著名文学家、书法家、画家，历史治水名人。与父苏洵、弟苏辙三人并称“三苏”。苏轼是北宋中期文坛领袖，在诗、词、散文、书、画等方面取得很高成就。文纵横恣肆；诗题材广阔，清新豪健，善用夸张比喻，独具风格，与黄庭坚并称“苏黄”；词开豪放一派，与辛弃疾同是豪放派代表，并称“苏辛”；散文著述宏富，豪放自如，与欧阳修并称“欧苏”，为“唐宋八大家”之一。苏轼善书，“宋四家”之一；擅长文人画，尤擅墨竹、怪石、枯木等。与韩愈、柳宗元和欧阳修合称“千古文章四大家”。作品有《东坡七集》《东坡易传》《东坡乐府》《潇湘竹石图卷》《古木怪石图卷》等。',
    proseNum: 1129,
    famousSentenceNum: 5980,
  },
  {
    name: '苏轼',
    avatar: 'https://ziyuan.guwendao.net/authorImg300/sushi.jpg',
    dynasty: '宋代',
    desc: '苏轼，（1037年1月8日-1101年8月24日）字子瞻、和仲，号铁冠道人、东坡居士，世称苏东坡、苏仙，汉族，眉州眉山（四川省眉山市）人，祖籍河北栾城，北宋著名文学家、书法家、画家，历史治水名人。与父苏洵、弟苏辙三人并称“三苏”。苏轼是北宋中期文坛领袖，在诗、词、散文、书、画等方面取得很高成就。文纵横恣肆；诗题材广阔，清新豪健，善用夸张比喻，独具风格，与黄庭坚并称“苏黄”；词开豪放一派，与辛弃疾同是豪放派代表，并称“苏辛”；散文著述宏富，豪放自如，与欧阳修并称“欧苏”，为“唐宋八大家”之一。苏轼善书，“宋四家”之一；擅长文人画，尤擅墨竹、怪石、枯木等。与韩愈、柳宗元和欧阳修合称“千古文章四大家”。作品有《东坡七集》《东坡易传》《东坡乐府》《潇湘竹石图卷》《古木怪石图卷》等。',
    proseNum: 1129,
    famousSentenceNum: 5980,
  },
  {
    name: '苏轼',
    avatar: 'https://ziyuan.guwendao.net/authorImg300/sushi.jpg',
    dynasty: '宋代',
    desc: '苏轼，（1037年1月8日-1101年8月24日）字子瞻、和仲，号铁冠道人、东坡居士，世称苏东坡、苏仙，汉族，眉州眉山（四川省眉山市）人，祖籍河北栾城，北宋著名文学家、书法家、画家，历史治水名人。与父苏洵、弟苏辙三人并称“三苏”。苏轼是北宋中期文坛领袖，在诗、词、散文、书、画等方面取得很高成就。文纵横恣肆；诗题材广阔，清新豪健，善用夸张比喻，独具风格，与黄庭坚并称“苏黄”；词开豪放一派，与辛弃疾同是豪放派代表，并称“苏辛”；散文著述宏富，豪放自如，与欧阳修并称“欧苏”，为“唐宋八大家”之一。苏轼善书，“宋四家”之一；擅长文人画，尤擅墨竹、怪石、枯木等。与韩愈、柳宗元和欧阳修合称“千古文章四大家”。作品有《东坡七集》《东坡易传》《东坡乐府》《潇湘竹石图卷》《古木怪石图卷》等。',
    proseNum: 1129,
    famousSentenceNum: 5980,
  },
  {
    name: '苏轼',
    avatar: 'https://ziyuan.guwendao.net/authorImg300/sushi.jpg',
    dynasty: '宋代',
    desc: '苏轼，（1037年1月8日-1101年8月24日）字子瞻、和仲，号铁冠道人、东坡居士，世称苏东坡、苏仙，汉族，眉州眉山（四川省眉山市）人，祖籍河北栾城，北宋著名文学家、书法家、画家，历史治水名人。与父苏洵、弟苏辙三人并称“三苏”。苏轼是北宋中期文坛领袖，在诗、词、散文、书、画等方面取得很高成就。文纵横恣肆；诗题材广阔，清新豪健，善用夸张比喻，独具风格，与黄庭坚并称“苏黄”；词开豪放一派，与辛弃疾同是豪放派代表，并称“苏辛”；散文著述宏富，豪放自如，与欧阳修并称“欧苏”，为“唐宋八大家”之一。苏轼善书，“宋四家”之一；擅长文人画，尤擅墨竹、怪石、枯木等。与韩愈、柳宗元和欧阳修合称“千古文章四大家”。作品有《东坡七集》《东坡易传》《东坡乐府》《潇湘竹石图卷》《古木怪石图卷》等。',
    proseNum: 1129,
    famousSentenceNum: 5980,
  },
  {
    name: '苏轼',
    avatar: 'https://ziyuan.guwendao.net/authorImg300/sushi.jpg',
    dynasty: '宋代',
    desc: '苏轼，（1037年1月8日-1101年8月24日）字子瞻、和仲，号铁冠道人、东坡居士，世称苏东坡、苏仙，汉族，眉州眉山（四川省眉山市）人，祖籍河北栾城，北宋著名文学家、书法家、画家，历史治水名人。与父苏洵、弟苏辙三人并称“三苏”。苏轼是北宋中期文坛领袖，在诗、词、散文、书、画等方面取得很高成就。文纵横恣肆；诗题材广阔，清新豪健，善用夸张比喻，独具风格，与黄庭坚并称“苏黄”；词开豪放一派，与辛弃疾同是豪放派代表，并称“苏辛”；散文著述宏富，豪放自如，与欧阳修并称“欧苏”，为“唐宋八大家”之一。苏轼善书，“宋四家”之一；擅长文人画，尤擅墨竹、怪石、枯木等。与韩愈、柳宗元和欧阳修合称“千古文章四大家”。作品有《东坡七集》《东坡易传》《东坡乐府》《潇湘竹石图卷》《古木怪石图卷》等。',
    proseNum: 1129,
    famousSentenceNum: 5980,
  },
];

export const mockAncientBooks = [
  {
    name: '论语',
    avatar: 'https://ziyuan.guwendao.net/authorImg300/libai.jpg',
    dynasty: '春秋',
    desc: '《论语》是儒家学派的经典著作之一，由孔子的弟子及其再传弟子编撰而成。它以语录体和对话文体为主，记录了孔子及其弟子言行，集中体现了孔子的政治主张、伦理思想、道德观念及教育原则等。与《大学》《中庸》《孟子》《诗经》《尚书》《礼记》《易经》《春秋》并称“四书五经”。通行本《论语》共二十篇。',
    proseNum: 1129,
    famousSentenceNum: 5980,
  },
  {
    name: '史记',
    avatar: 'https://ziyuan.guwendao.net/authorImg300/sushi.jpg',
    dynasty: '汉代',
    desc: '《史记》是由司马迁撰写的中国第一部纪传体通史。记载了上自上古传说中的黄帝时代，下至汉武帝元狩元年间共3000多年的历史（哲学、政治、经济、军事等）。《史记》最初没有固定书名，或称“太史公书”，或称“太史公传”，也省称“太史公”。“史记”本是古代史书通称，从三国时期开始，“史记”由史书的通称逐渐成为“太史公书”的专称。《史记》与后来的《汉书》（班固）、《后汉书》（范晔、司马彪）、《三国志》（陈寿）合称“前四史”。刘向等人认为此书“善序事理，辩而不华，质而不俚”。与司马光的《资治通鉴》并称“史学双璧”。',
    proseNum: 1129,
    famousSentenceNum: 5980,
  },
  {
    name: '老子',
    avatar: 'https://ziyuan.guwendao.net/authorImg300/sushi.jpg',
    dynasty: '战国',
    desc: '《老子》，又称《道德真经》《道德经》《五千言》《老子五千文》，是中国古代先秦诸子分家前的一部著作，为其时诸子所共仰，传说是春秋时期的老子李耳（似是作者、注释者、传抄者的集合体）所撰写，是道家哲学思想的重要来源。道德经分上下两篇，原文上篇《德经》、下篇《道经》，不分章，后改为《道经》37章在前，从38章开始为《德经》，一共81章。是中国历史上首部完整的哲学著作。此版本为通行本。',
    proseNum: 1129,
    famousSentenceNum: 5980,
  },
  {
    name: '孙子兵法',
    avatar: 'https://ziyuan.guwendao.net/authorImg300/sushi.jpg',
    dynasty: '战国',
    desc: '《孙子兵法》又称《孙武兵法》《吴孙子兵法》《孙子兵书》《孙武兵书》等，是中国现存最早的兵书，也是世界上最早的军事著作，早于克劳塞维茨《战争论》约2300年，被誉为“兵学圣典”。共有六千字左右，一共十三篇。作者为春秋时祖籍齐国乐安的吴国将军孙武。《孙子兵法》是中国古代军事文化遗产中的璀璨瑰宝，优秀传统文化的重要组成部分，是古代军事思想精华的集中体现。',
    proseNum: 1129,
    famousSentenceNum: 5980,
  },
  {
    name: '山海经',
    avatar: 'https://ziyuan.guwendao.net/authorImg300/sushi.jpg',
    dynasty: '战国',
    desc: '《山海经》是中国志怪古籍，大体是战国中后期到汉代初中期的楚国或巴蜀人所作。也是一部荒诞不经的奇书。该书作者不详，古人认为该书是“战国好奇之士取《穆王传》，杂录《庄》《列》《离骚》《周书》《晋乘》以成者” 。现代学者也均认为成书并非一时，作者亦非一人。《山海经》全书现存18篇，其余篇章内容早佚。原共22篇约32650字。共藏山经5篇、海外经4篇、海内经5篇、大荒经4篇。《汉书·艺文志》作13篇，未把晚出的大荒经和海内经计算在内。《山海经》包含着关于上古地理、历史、神话、天文、动物、植物、医学以及人类学、民族学、海洋学和科技史等方面的诸多内容，是一部上古社会生活的百科全书。',
    proseNum: 1129,
    famousSentenceNum: 5980,
  },
];

export const mockFamousSentence = [
  {
    sentence: '俏也不争春，只把春来报。',
    author: '毛泽东',
    title: '卜算子',
  },
  {
    sentence: '一去隔绝国，思归但长嗟。',
    author: '李白',
    title: '千里思',
  },
  {
    sentence: '斑骓只系垂杨岸，何处西南任好风。',
    author: '李商隐',
    title: '无题·凤尾香罗薄几重',
  },
  {
    sentence: '俏也不争春，只把春来报。',
    author: '毛泽东',
    title: '卜算子',
  },
  {
    sentence: '俏也不争春，只把春来报。',
    author: '毛泽东',
    title: '卜算子',
  },
  {
    sentence: '俏也不争春，只把春来报。',
    author: '毛泽东',
    title: '卜算子',
  },
  {
    sentence: '俏也不争春，只把春来报。',
    author: '毛泽东',
    title: '卜算子',
  },
  {
    sentence: '俏也不争春，只把春来报。',
    author: '毛泽东',
    title: '卜算子',
  },
];

export const mockAsideTags = [
  { label: '诗经', href: 'www.baidu.com' },
  { label: '乐府', href: 'www.baidu.com' },
  { label: '唐诗三百', href: 'www.baidu.com' },
  { label: '楚辞', href: 'www.baidu.com' },
  { label: '唐诗三百', href: 'www.baidu.com' },
  { label: '唐诗三百', href: 'www.baidu.com' },
  { label: '咏物', href: 'www.baidu.com' },
  { label: '唐诗三百', href: 'www.baidu.com' },
  { label: '唐诗三百', href: 'www.baidu.com' },
  { label: '唐诗三百', href: 'www.baidu.com' },
  { label: '唐诗三百', href: 'www.baidu.com' },
  { label: '唐诗三百', href: 'www.baidu.com' },
];

export const mockDynastyTags = [
  {
    type: '1',
    name: '朝代',
    list: [
      { label: '不限', href: 'www.baidu.com' },
      { label: '先秦', href: 'www.baidu.com' },
      { label: '两汉', href: 'www.baidu.com' },
      { label: '魏晋', href: 'www.baidu.com' },
      { label: '南北朝', href: 'www.baidu.com' },
      { label: '隋代', href: 'www.baidu.com' },
      { label: '唐代', href: 'www.baidu.com' },
      { label: '五代', href: 'www.baidu.com' },
      { label: '宋代', href: 'www.baidu.com' },
      { label: '金朝', href: 'www.baidu.com' },
      { label: '元代', href: 'www.baidu.com' },
      { label: '明代', href: 'www.baidu.com' },
      { label: '清代', href: 'www.baidu.com' },
    ],
    expand: false,
  },
];

export const ancientBooksTags = [
  {
    type: '1',
    name: '经部',
    list: [
      { label: '书类', href: 'www.baidu.com' },
      { label: '诗类', href: 'www.baidu.com' },
      { label: '礼类', href: 'www.baidu.com' },
      { label: '春秋类', href: 'www.baidu.com' },
      { label: '孝经类', href: 'www.baidu.com' },
      { label: '五经总义类', href: 'www.baidu.com' },
      { label: '四书类', href: 'www.baidu.com' },
      { label: '乐类', href: 'www.baidu.com' },
      { label: '小学类', href: 'www.baidu.com' },
    ],
    expand: false,
  },
  {
    type: '2',
    name: '史部',
    list: [
      { label: '正史类', href: 'www.baidu.com' },
      { label: '编年类', href: 'www.baidu.com' },
      { label: '纪事本未类', href: 'www.baidu.com' },
      { label: '杂史类', href: 'www.baidu.com' },
      { label: '别史类', href: 'www.baidu.com' },
      { label: '诏令奏议类', href: 'www.baidu.com' },
      { label: '传记类', href: 'www.baidu.com' },
      { label: '史钞类', href: 'www.baidu.com' },
      { label: '载记类', href: 'www.baidu.com' },
      { label: '时令类', href: 'www.baidu.com' },
      { label: '地理类', href: 'www.baidu.com' },
    ],
    expand: false,
  },
  {
    type: '3',
    name: '子部',
    list: [
      { label: '儒家类', href: 'www.baidu.com' },
      { label: '兵家类', href: 'www.baidu.com' },
      { label: '法家类', href: 'www.baidu.com' },
      { label: '农家类', href: 'www.baidu.com' },
      { label: '医家类', href: 'www.baidu.com' },
      { label: '天文算法类', href: 'www.baidu.com' },
      { label: '术数类', href: 'www.baidu.com' },
      { label: '艺术类', href: 'www.baidu.com' },
      { label: '谱录类', href: 'www.baidu.com' },
      { label: '杂家类', href: 'www.baidu.com' },
      { label: '类书类', href: 'www.baidu.com' },
      { label: '小说家类', href: 'www.baidu.com' },
    ],
    expand: false,
  },
  {
    type: '4',
    name: '集部',
    list: [
      { label: '楚辞类', href: 'www.baidu.com' },
      { label: '别集类', href: 'www.baidu.com' },
      { label: '总集类', href: 'www.baidu.com' },
      { label: '诗文评类', href: 'www.baidu.com' },
      { label: '词曲类', href: 'www.baidu.com' },
    ],
    expand: false,
  },
];

export const mockRecommendTags = [
  {
    type: '1',
    name: '类型',
    list: [
      { label: '诗经', href: 'www.baidu.com' },
      { label: '乐府', href: 'www.baidu.com' },
      { label: '楚辞', href: 'www.baidu.com' },
      { label: '送别', href: 'www.baidu.com' },
      { label: '劝学', href: 'www.baidu.com' },
      { label: '边塞', href: 'www.baidu.com' },
      { label: '儿童', href: 'www.baidu.com' },
      { label: '春天', href: 'www.baidu.com' },
      { label: '夏天', href: 'www.baidu.com' },
      { label: '秋天', href: 'www.baidu.com' },
      { label: '冬天', href: 'www.baidu.com' },
      { label: '悲愤', href: 'www.baidu.com' },
      { label: '悼亡', href: 'www.baidu.com' },
      { label: '咏怀', href: 'www.baidu.com' },
      { label: '爱国', href: 'www.baidu.com' },
      { label: '思乡', href: 'www.baidu.com' },
      { label: '爱情', href: 'www.baidu.com' },
      { label: '田园', href: 'www.baidu.com' },
    ],
    expand: false,
  },
  {
    type: '2',
    name: '作者',
    list: [
      { label: '诗经', href: 'www.baidu.com' },
      { label: '乐府', href: 'www.baidu.com' },
      { label: '楚辞', href: 'www.baidu.com' },
      { label: '送别', href: 'www.baidu.com' },
      { label: '劝学', href: 'www.baidu.com' },
      { label: '边塞', href: 'www.baidu.com' },
      { label: '儿童', href: 'www.baidu.com' },
      { label: '春天', href: 'www.baidu.com' },
      { label: '夏天', href: 'www.baidu.com' },
      { label: '秋天', href: 'www.baidu.com' },
      { label: '冬天', href: 'www.baidu.com' },
      { label: '悲愤', href: 'www.baidu.com' },
      { label: '悼亡', href: 'www.baidu.com' },
      { label: '咏怀', href: 'www.baidu.com' },
      { label: '爱国', href: 'www.baidu.com' },
      { label: '思乡', href: 'www.baidu.com' },
      { label: '爱情', href: 'www.baidu.com' },
      { label: '田园', href: 'www.baidu.com' },
    ],
    expand: false,
  },
  {
    type: '3',
    name: '朝代',
    list: [
      { label: '诗经', href: 'www.baidu.com' },
      { label: '乐府', href: 'www.baidu.com' },
      { label: '楚辞', href: 'www.baidu.com' },
      { label: '送别', href: 'www.baidu.com' },
      { label: '劝学', href: 'www.baidu.com' },
      { label: '边塞', href: 'www.baidu.com' },
      { label: '儿童', href: 'www.baidu.com' },
      { label: '春天', href: 'www.baidu.com' },
      { label: '夏天', href: 'www.baidu.com' },
      { label: '秋天', href: 'www.baidu.com' },
      { label: '冬天', href: 'www.baidu.com' },
      { label: '悲愤', href: 'www.baidu.com' },
      { label: '悼亡', href: 'www.baidu.com' },
      { label: '咏怀', href: 'www.baidu.com' },
      { label: '爱国', href: 'www.baidu.com' },
      { label: '思乡', href: 'www.baidu.com' },
      { label: '爱情', href: 'www.baidu.com' },
      { label: '田园', href: 'www.baidu.com' },
    ],
    expand: false,
  },
  {
    type: '4',
    name: '形式',
    list: [
      { label: '诗经', href: 'www.baidu.com' },
      { label: '乐府', href: 'www.baidu.com' },
      { label: '楚辞', href: 'www.baidu.com' },
      { label: '送别', href: 'www.baidu.com' },
      { label: '劝学', href: 'www.baidu.com' },
      { label: '边塞', href: 'www.baidu.com' },
      { label: '儿童', href: 'www.baidu.com' },
      { label: '春天', href: 'www.baidu.com' },
      { label: '夏天', href: 'www.baidu.com' },
      { label: '秋天', href: 'www.baidu.com' },
      { label: '冬天', href: 'www.baidu.com' },
      { label: '悲愤', href: 'www.baidu.com' },
      { label: '悼亡', href: 'www.baidu.com' },
      { label: '咏怀', href: 'www.baidu.com' },
      { label: '爱国', href: 'www.baidu.com' },
      { label: '思乡', href: 'www.baidu.com' },
      { label: '爱情', href: 'www.baidu.com' },
      { label: '田园', href: 'www.baidu.com' },
    ],
    expand: false,
  },
];
